onedrive_url: "https://1drv.ms/x/c/03c73def4fac5feb/EetfrE_vPccggANuAAAAAAABbFn-LkxXlrs7q6s51K_67Q?e=ZRSZqm&download=1"
onedrive_sheet_name: "BASE ASMA"
onedrive_col_final: "IZ"
gspreadsheet_id: "1XLxI_hb_tBCg8Ko7o6VPz1haLUlOf1L4IYmVgzNqQ7I"
gspreadsheet_sheet_name: "Data"
skiprows: 6
column_names:
  - pte_tipo_documento
  - pte_documento
  - pte_primer_nombre
  - pte_segundo_nombre
  - pte_primer_apellido
  - pte_segundo_apellido
  - pte_codigo_interno_paciente
  - pte_medico_tratante
  - pte_lugar_residencia
  - pte_sede
  - pte_genero
  - pte_fecha_nacimiento
  - pte_edad
  - pte_rango_edad
  - pte_eps
  - pte_fecha_ingreso_programa
  - pte_mes_ruta
  - pte_estado
  - pte_diagnostico_previo_asma
  - mes0_fecha_espirometria
  - mes0_peso_kg
  - mes0_talla_cm
  - mes0_cvf_pre_l
  - mes0_cvf_pre_porc
  - mes0_vef1_pre_l
  - mes0_vef1_pre_porc
  - mes0_vef1xcvf_pre_l
  - mes0_vef1xcvf_pre_porc
  - mes0_cvf_post_l
  - mes0_cvf_post_porc
  - mes0_vef1_post_l
  - mes0_vef1_post_porc
  - mes0_vef1xcvf_post_l
  - mes0_vef1xcvf_post_porc
  - mes0_respuesta_broncodilatador_1
  - mes0_oscilometria
  - mes0_fecha_oscilometria
  - mes0_interpretacion_oscilometria
  - mes0_respuesta_broncodilatador_2
  - mes0_feno
  - mes0_fecha_feno
  - mes0_resultado_feno
  - mes0_prueba_broncoprovocacion
  - mes0_fecha_prueba_broncoprobocacion
  - mes0_interpretacion_p_broncoprovocacion
  - mes0_calidad_vida
  - mes0_interpretacion_calidad_vida
  - mes0_tai
  - mes0_interpretacion_tai
  - mes0_act
  - mes0_interpretacion_act
  - mes0_acq
  - mes0_interpretacion_acq
  - mes0_exacerbaciones
  - mes0_manejo_exacerbacion_casa_cant
  - mes0_manejo_exacerbacion_cita_prioritaria_cant
  - mes0_manejo_exacerbacion_urgencias_cant
  - mes0_manejo_exacerbacion_hospitalizacion_cant
  - mes0_manejo_exacerbacion_uci_cant
  - mes0_manejo_exacerbaciones_corticosteroides
  - mes0_paciente_sospecha_asma_alergica
  - mes0_fecha_valoracion_alergologia
  - mes0_fecha_prick_test
  - mes0_resultado_prick_test
  - mes0_corticoide_inhalado_si_no
  - mes0_corticoide_inhalado_detalle
  - mes0_gci_laba_si_no
  - mes0_gci_laba_detalle
  - mes0_saba_si_no
  - mes0_saba_detalle
  - mes0_lama_si_no
  - mes0_lama_detalle
  - mes0_terapia_biologica_si_no
  - mes0_terapia_biologica_detalle
  - mes0_fecha_junta_asma_para_formulacion
  - mes0_fecha_inicio_terapia_biologica
  - mes0_alerta_seguimiento_mes_6
  - mes0_alerta_seguimiento_mes_12
  - mes0_paciente_eventos_adversos
  - mes0_fecha_ultimo_evento_adverso
  - mes0_fecha_entrega_plan_accion
  - mes1_fecha_entrega_educacion_tics_mes_1
  - mes1_fecha_seguimiento_mes_1
  - mes2_fecha_entrega_educacion_tics_mes_2
  - mes2_fecha_seguimiento_mes_2
  - mes3_fecha_entrega_educacion_tics_mes_3
  - mes3_fecha_seguimiento
  - mes3_tai
  - mes3_interpretacion_tai
  - mes3_act
  - mes3_interpretacion_act
  - mes3_acq
  - mes3_interpretacion_acq
  - mes3_exacerbaciones
  - mes3_manejo_exacerbacion_casa_cant
  - mes3_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes3_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes3_manejo_exacerbacion_urgencias_cant
  - mes3_manejo_exacerbacion_hospitalizacion_cant
  - mes3_manejo_exacerbacion_uci_cant
  - mes3_manejo_exacerbaciones_corticosteroides
  - mes3_cantidad_citas_prioritarias_fase_1
  - mes3_junta_asma_fase_1
  - mes3_fecha_real_cita_neumologia_3_mes
  - mes3_confirmacion_diagnostica
  - mes3_fecha_confirmacion_diagnostica
  - mes3_fecha_estudio_diagnostico_previo
  - mes3_soporte_prueba_diagnostico
  - mes3_paciente_inicia_rehabilitacion_pulmonar
  - mes3_modalidad_atencion_rehabilitacion_pulmonar_inicio
  - mes3_caminata_6_minutos_inicial_mts
  - mes3_grupo_riesgo
  - mes3_gravedad_enfermedad
  - mes3_fecha_valoracion_nutricion
  - mes3_requiere_seguimiento_nutricion
  - mes3_fecha_seguimiento_nutricion
  - mes3_fecha_valoracion_psicologia
  - mes3_requiere_seguimiento_psicologia
  - mes3_fecha_seguimiento_psicologia
  - mes4_fecha_entrega_educacion_tics
  - mes5_fecha_entrega_educacion_tics
  - mes6_fecha_entrega_educacion_tics
  - mes6_fecha_seguimiento
  - mes6_tai
  - mes6_interpretacion_tai
  - mes6_act
  - mes6_interpretacion_act
  - mes6_acq
  - mes6_interpretacion_acq
  - mes6_exacerbaciones
  - mes6_manejo_exacerbacion_casa_cant
  - mes6_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes6_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes6_manejo_exacerbacion_urgencias_cant
  - mes6_manejo_exacerbacion_hospitalizacion_cant
  - mes6_manejo_exacerbacion_uci_cant
  - mes6_manejo_exacerbaciones_corticosteroides
  - mes6_fecha_real_cita_neumologia
  - mes7_fecha_entrega_educacion_tics
  - mes8_fecha_entrega_educacion_tics
  - mes9_fecha_entrega_educacion_tics
  - mes9_fecha_seguimiento_mes
  - mes9_tai
  - mes9_interpretacion_tai
  - mes9_act
  - mes9_interpretacion_act
  - mes9_acq
  - mes9_interpretacion_acq
  - mes9_exacerbaciones
  - mes9_manejo_exacerbacion_casa_cant
  - mes9_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes9_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes9_manejo_exacerbacion_urgencias_cant
  - mes9_manejo_exacerbacion_hospitalizacion_cant
  - mes9_manejo_exacerbacion_uci_cant
  - mes9_manejo_exacerbaciones_corticosteroides
  - mes9_fecha_real_cita_neumologia
  - mes10_fecha_entrega_educacion_tics
  - mes11_fecha_entrega_educacion_tics
  - mes12_fecha_entrega_educacion_tics
  - mes12_fecha_seguimiento
  - mes12_cantidad_valoraciones_alergologia_fase_seguimiento
  - mes12_calidad_vida
  - mes12_interpretacion_calidad_vida
  - mes12_tai
  - mes12_interpretacion_tai
  - mes12_act
  - mes12_interpretacion_act
  - mes12_acq
  - mes12_interpretacion_acq
  - mes12_exacerbaciones
  - mes12_manejo_exacerbacion_casa_cant
  - mes12_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes12_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes12_manejo_exacerbacion_urgencias_cant
  - mes12_manejo_exacerbacion_hospitalizacion_cant
  - mes12_manejo_exacerbacion_uci_cant
  - mes12_manejo_exacerbaciones_corticosteroides
  - mes12_cantidad_citas_prioritarias_fase_2
  - mes12_junta_asma_fase_2
  - mes12_fecha_espirometria
  - mes12_peso_kg
  - mes12_talla_cm
  - mes12_cvf_pre_l
  - mes12_cvf_pre_porc
  - mes12_vef_pre_l
  - mes12_vef_pre_porc
  - mes12_vef1xcvf_pre_l
  - mes12_vef1xcvf_pre_porc
  - mes12_cvf_post_l
  - mes12_cvf_post_porc
  - mes12_vef_post_l
  - mes12_vef_post_porc
  - mes12_vef1xcvf_post_l
  - mes12_vef1xcvf_post_porc
  - mes12_oscilometria
  - mes12_interpretacion_oscilometria
  - mes12_fecha_real_cita_neumologia
  - mes13_exacerbaciones
  - mes13_manejo_exacerbacion_casa_cant
  - mes13_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes13_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes13_manejo_exacerbacion_urgencias_cant
  - mes13_manejo_exacerbacion_hospitalizacion_cant
  - mes13_manejo_exacerbacion_uci_cant
  - mes13_manejo_exacerbaciones_corticosteroides
  - mes12_paciente_finalizo_rehabilitacion_pulmonar
  - mes12_modalidad_atencion_rehabilitacion_pulmonar_fin
  - mes12_caminata_6_minutos_final_mts
  - mes12_cambios_alcanzados_c6m
  - mes13_fecha_entrega_educacion_tics
  - mes14_fecha_entrega_educacion_tics
  - mes15_fecha_entrega_educacion_tics
  - mes15_fecha_seguimiento
  - mes15_tai
  - mes15_interpretacion_tai
  - mes15_act
  - mes15_interpretacion_act
  - mes15_acq
  - mes15_interpretacion_acq
  - mes15_exacerbaciones
  - mes15_manejo_exacerbacion_casa_cant
  - mes15_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes15_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes15_manejo_exacerbacion_urgencias_cant
  - mes15_manejo_exacerbacion_hospitalizacion_cant
  - mes15_manejo_exacerbacion_uci_cant
  - mes15_manejo_exacerbaciones_corticosteroides
  - mes15_fecha_real_cita_neumologia
  - mes16_fecha_entrega_educacion_tics
  - mes17_fecha_entrega_educacion_tics
  - mes18_fecha_entrega_educacion_tics
  - mes18_fecha_seguimiento
  - mes18_tai
  - mes18_interpretacion_tai
  - mes18_act
  - mes18_interpretacion_act
  - mes18_acq
  - mes18_interpretacion_acq
  - mes18_exacerbaciones
  - mes18_manejo_exacerbacion_casa_cant
  - mes18_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes18_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes18_manejo_exacerbacion_urgencias_cant
  - mes18_manejo_exacerbacion_hospitalizacion_cant
  - mes18_manejo_exacerbacion_uci_cant
  - mes18_manejo_exacerbaciones_corticosteroides
  - mes18_fecha_real_cita_neumologia
  - total_exacerbaciones_total
  - total_exacerbaciones_leves
  - total_exacerbaciones_graves
  - total_n_entregas_educacion_tics
  - total_entregas_educacion_tics_completas
  - total_evaluacion_adherencia
  - total_paciente_egreso_temprano
  - total_fecha_egreso_temprano
  - total_egreso
  - total_fecha_egreso
  - total_motivo_egreso
  - total_observaciones_gestora
numeric_columns:
  - pte_edad
  - pte_mes_ruta
  - mes0_peso_kg
  - mes0_talla_cm
  - mes0_cvf_pre_l
  - mes0_cvf_pre_porc
  - mes0_vef1_pre_l
  - mes0_vef1_pre_porc
  - mes0_vef1xcvf_pre_l
  - mes0_vef1xcvf_pre_porc
  - mes0_cvf_post_l
  - mes0_cvf_post_porc
  - mes0_vef1_post_l
  - mes0_vef1_post_porc
  - mes0_vef1xcvf_post_l
  - mes0_vef1xcvf_post_porc
  - mes0_resultado_feno
  - mes0_calidad_vida
  - mes0_tai
  - mes0_act
  - mes0_acq
  - mes0_manejo_exacerbacion_casa_cant
  - mes0_manejo_exacerbacion_cita_prioritaria_cant
  - mes0_manejo_exacerbacion_urgencias_cant
  - mes0_manejo_exacerbacion_hospitalizacion_cant
  - mes0_manejo_exacerbacion_uci_cant
  - mes0_alerta_seguimiento_mes_6
  - mes0_alerta_seguimiento_mes_12
  - mes3_tai
  - mes3_act
  - mes3_acq
  - mes3_manejo_exacerbacion_casa_cant
  - mes3_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes3_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes3_manejo_exacerbacion_urgencias_cant
  - mes3_manejo_exacerbacion_hospitalizacion_cant
  - mes3_manejo_exacerbacion_uci_cant
  - mes3_cantidad_citas_prioritarias_fase_1
  - mes3_caminata_6_minutos_inicial_mts
  - mes6_tai
  - mes6_act
  - mes6_acq
  - mes6_manejo_exacerbacion_casa_cant
  - mes6_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes6_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes6_manejo_exacerbacion_urgencias_cant
  - mes6_manejo_exacerbacion_hospitalizacion_cant
  - mes6_manejo_exacerbacion_uci_cant
  - mes9_tai
  - mes9_act
  - mes9_acq
  - mes9_manejo_exacerbacion_casa_cant
  - mes9_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes9_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes9_manejo_exacerbacion_urgencias_cant
  - mes9_manejo_exacerbacion_hospitalizacion_cant
  - mes9_manejo_exacerbacion_uci_cant
  - mes12_cantidad_valoraciones_alergologia_fase_seguimiento
  - mes12_calidad_vida
  - mes12_tai
  - mes12_act
  - mes12_acq
  - mes12_manejo_exacerbacion_casa_cant
  - mes12_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes12_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes12_manejo_exacerbacion_urgencias_cant
  - mes12_manejo_exacerbacion_hospitalizacion_cant
  - mes12_manejo_exacerbacion_uci_cant
  - mes12_cantidad_citas_prioritarias_fase_2
  - mes12_peso_kg
  - mes12_talla_cm
  - mes12_cvf_pre_l
  - mes12_cvf_pre_porc
  - mes12_vef_pre_l
  - mes12_vef_pre_porc
  - mes12_vef1xcvf_pre_l
  - mes12_vef1xcvf_pre_porc
  - mes12_cvf_post_l
  - mes12_cvf_post_porc
  - mes12_vef_post_l
  - mes12_vef_post_porc
  - mes12_vef1xcvf_post_l
  - mes12_vef1xcvf_post_porc
  - mes13_manejo_exacerbacion_casa_cant
  - mes13_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes13_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes13_manejo_exacerbacion_urgencias_cant
  - mes13_manejo_exacerbacion_hospitalizacion_cant
  - mes13_manejo_exacerbacion_uci_cant
  - mes12_caminata_6_minutos_final_mts
  - mes12_cambios_alcanzados_c6m
  - mes15_tai
  - mes15_act
  - mes15_acq
  - mes15_manejo_exacerbacion_casa_cant
  - mes15_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes15_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes15_manejo_exacerbacion_urgencias_cant
  - mes15_manejo_exacerbacion_hospitalizacion_cant
  - mes15_manejo_exacerbacion_uci_cant
  - mes18_tai
  - mes18_act
  - mes18_acq
  - mes18_manejo_exacerbacion_casa_cant
  - mes18_manejo_exacerbacion_cita_prioritaria_ino_cant
  - mes18_manejo_exacerbacion_cita_prioritaria_no_ino_cant
  - mes18_manejo_exacerbacion_urgencias_cant
  - mes18_manejo_exacerbacion_hospitalizacion_cant
  - mes18_manejo_exacerbacion_uci_cant
  - total_exacerbaciones_total
  - total_exacerbaciones_leves
  - total_exacerbaciones_graves
  - total_n_entregas_educacion_tics
  - total_evaluacion_adherencia
date_columns:
  - pte_fecha_nacimiento
  - pte_fecha_ingreso_programa
  - total_fecha_egreso