gspreadsheet_id: "1XLxI_hb_tBCg8Ko7o6VPz1haLUlOf1L4IYmVgzNqQ7I"
gspreadsheet_sheet_name: "Data"
bq_project_id: "observatorio-ino-1"
bq_dataset_id: "rehabilitacion_pulmonar"
bq_table_id: "tbl_asma"
campo_fecha_particion: "pte_fecha_ingreso_programa"
campos_date:
  - pte_fecha_nacimiento
  - pte_fecha_ingreso_programa
  - total_fecha_egreso